// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241207102845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "711255cc-ff15-43e7-8812-9e21981b4921",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "25ceffff-03eb-48d1-974b-67708bf1ac6c",
                            Name = "Individual",
                            NormalizedName = "INDIVIDUAL"
                        },
                        new
                        {
                            Id = "75be44f7-14a1-4bb6-a56a-875f6c811f51",
                            Name = "Business",
                            NormalizedName = "BUSINESS"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("api.Models.Action", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActionId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("api.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogId");

                    b.HasIndex("ActionId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d5511b0-3cdd-4a4a-99d5-2c98e52c96ec",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "admin1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eef3bfd8-9460-43eb-8474-c2f06cac675b",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d5bea72-d21e-4f82-b217-64e777210d79",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "admin2@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a83461e-02c4-4734-9462-a6f2e0ea19a1",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "admin2"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acb7ef53-dd82-4a1f-9088-773824d699f0",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "admin3@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76a75bf3-7331-48b7-a879-a4368da74a8e",
                            Status = "Blocked",
                            TwoFactorEnabled = false,
                            UserName = "admin3"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b5e6d2c-f6dd-49a7-9e79-4468d7dd07bf",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "admin4@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5eefa3a3-3e04-44d1-8248-955e8e0f0980",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "admin4"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a457ccec-c660-4ca5-96ed-f9d6364af6c8",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "admin5@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b7efdb26-d34f-4782-bea2-cf3d25709b65",
                            Status = "Pending",
                            TwoFactorEnabled = false,
                            UserName = "admin5"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a59accc3-0f8e-41f5-9560-fd9760b700b1",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "business1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64419605-2c54-4636-9c63-cee0b235fda0",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "business1"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "036db0fe-ae96-43ec-842f-828c2777956e",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "business2@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0af50ef4-5cf2-40b7-996d-3e355cfbe8b9",
                            Status = "Pending",
                            TwoFactorEnabled = false,
                            UserName = "business2"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5f90ddb-1408-4b95-8c22-a58af38d2dae",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "business3@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4044fb71-efc3-4c6f-b670-0d74bcb8ca33",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "business3"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd25cf05-9723-4bac-a45e-af51ec4d7424",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "business4@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "42449709-74d2-4fdc-b241-89c834bb69f2",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "business4"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d498d51-57a0-490b-a28b-2bd6ce96b73e",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "business5@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "807a4a10-d624-4c27-a27a-07318daed04e",
                            Status = "Pending",
                            TwoFactorEnabled = false,
                            UserName = "business5"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88ef9bc1-09b5-44a0-b421-638b588e6090",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "individual1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "097ae36f-fa27-4bdb-9304-98aed57ce155",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "individual1"
                        },
                        new
                        {
                            Id = "12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcb3b21d-a9c4-4e59-8727-354f82aa6a10",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "individual2@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "367186e5-6dd7-472a-9937-c91c225acb40",
                            Status = "Blocked",
                            TwoFactorEnabled = false,
                            UserName = "individual2"
                        },
                        new
                        {
                            Id = "13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e88b3b9-ad1e-4ceb-afe0-8746427ccb71",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "individual3@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aafb32cd-de2a-4e05-a4e8-591bfafc0006",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "individual3"
                        },
                        new
                        {
                            Id = "14",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7702e073-abd2-4871-b936-6b3b611c70a6",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "individual4@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db764433-2314-4791-95c8-bcf704035697",
                            Status = "Pending",
                            TwoFactorEnabled = false,
                            UserName = "individual4"
                        },
                        new
                        {
                            Id = "15",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d7a10ea-95ff-40fe-ac7e-651743dfa303",
                            CreatedAt = new DateTime(2024, 12, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(1808),
                            Email = "individual5@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50428ff4-dbd2-4521-993a-0f93248a3acd",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "individual5"
                        });
                });

            modelBuilder.Entity("api.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuctionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentBid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReservePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuctionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            AuctionId = 1,
                            Address = "{\"city\": \"New York\", \"state\": \"NY\"}",
                            AuctionStatus = "Started",
                            CategoryId = 1,
                            Condition = "Mixed",
                            CreatedAt = new DateTime(2024, 11, 27, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2657),
                            CurrentBid = 650.00m,
                            Description = "A collection of high-grade aluminum scraps.",
                            EndingTime = new DateTime(2024, 12, 12, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2668),
                            Images = "[\"aluminum1.jpg\", \"aluminum2.jpg\"]",
                            Quantity = 100m,
                            ReservePrice = 800.00m,
                            SellerId = "4",
                            StartingBid = 500.00m,
                            StartingTime = new DateTime(2024, 12, 2, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2667),
                            Title = "Aluminum Scrap Bundle"
                        },
                        new
                        {
                            AuctionId = 2,
                            Address = "{\"city\": \"Los Angeles\", \"state\": \"CA\"}",
                            AuctionStatus = "Ended",
                            CategoryId = 2,
                            Condition = "Used",
                            CreatedAt = new DateTime(2024, 11, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2682),
                            CurrentBid = 1200.00m,
                            Description = "Various grades of copper wiring ready for recycling.",
                            EndingTime = new DateTime(2024, 11, 22, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2685),
                            Images = "[\"copper1.jpg\", \"copper2.jpg\"]",
                            Quantity = 200m,
                            ReservePrice = 1500.00m,
                            SellerId = "4",
                            StartingBid = 1000.00m,
                            StartingTime = new DateTime(2024, 11, 12, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2684),
                            Title = "Copper Wiring Scrap"
                        },
                        new
                        {
                            AuctionId = 3,
                            Address = "{\"city\": \"Houston\", \"state\": \"TX\"}",
                            AuctionStatus = "Started",
                            CategoryId = 3,
                            Condition = "New",
                            CreatedAt = new DateTime(2024, 12, 2, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2764),
                            CurrentBid = 450.00m,
                            Description = "Recyclable plastic waste from industrial sources.",
                            EndingTime = new DateTime(2024, 12, 14, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2768),
                            Images = "[\"plastic1.jpg\"]",
                            Quantity = 50m,
                            ReservePrice = 600.00m,
                            SellerId = "4",
                            StartingBid = 300.00m,
                            StartingTime = new DateTime(2024, 12, 4, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2766),
                            Title = "Plastic Waste"
                        },
                        new
                        {
                            AuctionId = 4,
                            Address = "{\"city\": \"Chicago\", \"state\": \"IL\"}",
                            AuctionStatus = "Ended",
                            CategoryId = 4,
                            Condition = "Used",
                            CreatedAt = new DateTime(2024, 11, 17, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2776),
                            CurrentBid = 800.00m,
                            Description = "Scrap iron sheets from old construction projects.",
                            EndingTime = new DateTime(2024, 11, 27, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2779),
                            Images = "[\"iron1.jpg\", \"iron2.jpg\"]",
                            Quantity = 300m,
                            ReservePrice = 1000.00m,
                            SellerId = "4",
                            StartingBid = 700.00m,
                            StartingTime = new DateTime(2024, 11, 19, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2777),
                            Title = "Iron Sheets"
                        },
                        new
                        {
                            AuctionId = 5,
                            Address = "{\"city\": \"Dallas\", \"state\": \"TX\"}",
                            AuctionStatus = "Started",
                            CategoryId = 5,
                            Condition = "New",
                            CreatedAt = new DateTime(2024, 11, 29, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2789),
                            CurrentBid = 1600.00m,
                            Description = "Premium-grade stainless steel scrap materials.",
                            EndingTime = new DateTime(2024, 12, 10, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2792),
                            Images = "[\"steel1.jpg\", \"steel2.jpg\"]",
                            Quantity = 150m,
                            ReservePrice = 2000.00m,
                            SellerId = "4",
                            StartingBid = 1500.00m,
                            StartingTime = new DateTime(2024, 11, 30, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2791),
                            Title = "Stainless Steel Scraps"
                        },
                        new
                        {
                            AuctionId = 6,
                            Address = "{\"city\": \"Atlanta\", \"state\": \"GA\"}",
                            AuctionStatus = "Ended",
                            CategoryId = 6,
                            Condition = "Mixed",
                            CreatedAt = new DateTime(2024, 10, 18, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2801),
                            CurrentBid = 250.00m,
                            Description = "Recyclable wooden pallets from warehouses.",
                            EndingTime = new DateTime(2024, 10, 28, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2804),
                            Images = "[\"wood1.jpg\", \"wood2.jpg\"]",
                            Quantity = 500m,
                            ReservePrice = 300.00m,
                            SellerId = "4",
                            StartingBid = 200.00m,
                            StartingTime = new DateTime(2024, 10, 20, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2802),
                            Title = "Wooden Pallets"
                        },
                        new
                        {
                            AuctionId = 7,
                            Address = "{\"city\": \"Phoenix\", \"state\": \"AZ\"}",
                            AuctionStatus = "Started",
                            CategoryId = 7,
                            Condition = "Used",
                            CreatedAt = new DateTime(2024, 11, 27, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2812),
                            CurrentBid = 550.00m,
                            Description = "Glass shards from old construction materials.",
                            EndingTime = new DateTime(2024, 12, 9, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2815),
                            Images = "[\"glass1.jpg\"]",
                            Quantity = 250m,
                            ReservePrice = 700.00m,
                            SellerId = "4",
                            StartingBid = 400.00m,
                            StartingTime = new DateTime(2024, 11, 30, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2813),
                            Title = "Glass Shards"
                        },
                        new
                        {
                            AuctionId = 8,
                            Address = "{\"city\": \"Seattle\", \"state\": \"WA\"}",
                            AuctionStatus = "Ended",
                            CategoryId = 8,
                            Condition = "Mixed",
                            CreatedAt = new DateTime(2024, 11, 12, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2823),
                            CurrentBid = 150.00m,
                            Description = "Paper waste from old documents and magazines.",
                            EndingTime = new DateTime(2024, 11, 22, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2826),
                            Images = "[\"paper1.jpg\"]",
                            Quantity = 1000m,
                            ReservePrice = 200.00m,
                            SellerId = "4",
                            StartingBid = 100.00m,
                            StartingTime = new DateTime(2024, 11, 17, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2825),
                            Title = "Paper Waste"
                        },
                        new
                        {
                            AuctionId = 9,
                            Address = "{\"city\": \"San Francisco\", \"state\": \"CA\"}",
                            AuctionStatus = "Started",
                            CategoryId = 9,
                            Condition = "Used",
                            CreatedAt = new DateTime(2024, 12, 2, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2835),
                            CurrentBid = 350.00m,
                            Description = "Used rubber tires ready for recycling.",
                            EndingTime = new DateTime(2024, 12, 13, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2838),
                            Images = "[\"rubber1.jpg\"]",
                            Quantity = 400m,
                            ReservePrice = 500.00m,
                            SellerId = "4",
                            StartingBid = 300.00m,
                            StartingTime = new DateTime(2024, 12, 3, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2837),
                            Title = "Rubber Tires"
                        },
                        new
                        {
                            AuctionId = 10,
                            Address = "{\"city\": \"Denver\", \"state\": \"CO\"}",
                            AuctionStatus = "Ended",
                            CategoryId = 11,
                            Condition = "Used",
                            CreatedAt = new DateTime(2024, 11, 7, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2846),
                            CurrentBid = 600.00m,
                            Description = "Scrap ceramic tiles from construction sites.",
                            EndingTime = new DateTime(2024, 11, 19, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2849),
                            Images = "[\"ceramic1.jpg\"]",
                            Quantity = 50m,
                            ReservePrice = 700.00m,
                            SellerId = "4",
                            StartingBid = 500.00m,
                            StartingTime = new DateTime(2024, 11, 9, 10, 28, 43, 884, DateTimeKind.Utc).AddTicks(2848),
                            Title = "Ceramic Tiles"
                        });
                });

            modelBuilder.Entity("api.Models.BiddingHistory", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("BiddingHistory");
                });

            modelBuilder.Entity("api.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BusinessServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessType")
                        .HasColumnType("int");

                    b.Property<string>("CompanyVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryContactFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryContactLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryJobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BusinessId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "123 Main St, Amman, Jordan",
                            BusinessEmail = "business1@example.com",
                            BusinessName = "Business 1",
                            BusinessPhoneNumber = "123-456-7890",
                            BusinessServices = "",
                            BusinessType = 1,
                            CompanyVision = "",
                            Images = "",
                            LinkedIn = "",
                            PrimaryContactEmail = "contact@business1.com",
                            PrimaryContactFirstName = "John",
                            PrimaryContactLastName = "Doe",
                            PrimaryJobTitle = "CEO",
                            PrimaryPhoneNumber = "123-456-7890",
                            RegistrationNumber = "REG12345",
                            UserId = "6"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "123 Main St, Amman, Jordan",
                            BusinessEmail = "business2@example.com",
                            BusinessName = "Business 2",
                            BusinessPhoneNumber = "223-456-7890",
                            BusinessServices = "",
                            BusinessType = 1,
                            CompanyVision = "",
                            Images = "",
                            LinkedIn = "",
                            PrimaryContactEmail = "contact@business2.com",
                            PrimaryContactFirstName = "Alice",
                            PrimaryContactLastName = "Smith",
                            PrimaryJobTitle = "Manager",
                            PrimaryPhoneNumber = "223-456-7890",
                            RegistrationNumber = "REG22345",
                            UserId = "7"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "123 Main St, Amman, Jordan",
                            BusinessEmail = "business3@example.com",
                            BusinessName = "Business 3",
                            BusinessPhoneNumber = "323-456-7890",
                            BusinessServices = "",
                            BusinessType = 2,
                            CompanyVision = "",
                            Images = "",
                            LinkedIn = "",
                            PrimaryContactEmail = "contact@business3.com",
                            PrimaryContactFirstName = "Mark",
                            PrimaryContactLastName = "Brown",
                            PrimaryJobTitle = "Owner",
                            PrimaryPhoneNumber = "323-456-7890",
                            RegistrationNumber = "REG32345",
                            UserId = "8"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "123 Main St, Amman, Jordan",
                            BusinessEmail = "business4@example.com",
                            BusinessName = "Business 4",
                            BusinessPhoneNumber = "423-456-7890",
                            BusinessServices = "",
                            BusinessType = 1,
                            CompanyVision = "",
                            Images = "",
                            LinkedIn = "",
                            PrimaryContactEmail = "contact@business4.com",
                            PrimaryContactFirstName = "Linda",
                            PrimaryContactLastName = "Johnson",
                            PrimaryJobTitle = "CEO",
                            PrimaryPhoneNumber = "423-456-7890",
                            RegistrationNumber = "REG42345",
                            UserId = "9"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "123 Main St, Amman, Jordan",
                            BusinessEmail = "business5@example.com",
                            BusinessName = "Business 5",
                            BusinessPhoneNumber = "523-456-7890",
                            BusinessServices = "",
                            BusinessType = 1,
                            CompanyVision = "",
                            Images = "",
                            LinkedIn = "",
                            PrimaryContactEmail = "contact@business5.com",
                            PrimaryContactFirstName = "Sarah",
                            PrimaryContactLastName = "Williams",
                            PrimaryJobTitle = "Manager",
                            PrimaryPhoneNumber = "523-456-7890",
                            RegistrationNumber = "REG52345",
                            UserId = "10"
                        });
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Aluminum"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Copper"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Plastic"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Iron"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Stainless Steel"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Wood"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Glass"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Paper"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Rubber"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Textile"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Ceramic"
                        });
                });

            modelBuilder.Entity("api.Models.Individual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IndividualId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            IndividualId = 1,
                            Address = "{\"street\":\"123 Main St\",\"city\":\"Amman\",\"country\":\"Jordan\"}",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PhoneNumber = "987-654-3210",
                            UserId = "11"
                        },
                        new
                        {
                            IndividualId = 2,
                            Address = "{\"street\":\"456 Oak St\",\"city\":\"Amman\",\"country\":\"Jordan\"}",
                            FirstName = "Bob",
                            Image = "profilepic2.jpg",
                            LastName = "Johnson",
                            PhoneNumber = "987-654-3220",
                            UserId = "12"
                        },
                        new
                        {
                            IndividualId = 3,
                            Address = "{\"street\":\"789 Pine St\",\"city\":\"Amman\",\"country\":\"Jordan\"}",
                            FirstName = "Charlie",
                            Image = "profilepic3.jpg",
                            LastName = "Smith",
                            PhoneNumber = "987-654-3230",
                            UserId = "13"
                        },
                        new
                        {
                            IndividualId = 4,
                            Address = "{\"street\":\"123 Birch St\",\"city\":\"Amman\",\"country\":\"Jordan\"}",
                            FirstName = "David",
                            Image = "profilepic4.jpg",
                            LastName = "Davis",
                            PhoneNumber = "987-654-3240",
                            UserId = "14"
                        },
                        new
                        {
                            IndividualId = 5,
                            Address = "{\"street\":\"456 Maple St\",\"city\":\"Amman\",\"country\":\"Jordan\"}",
                            FirstName = "Eva",
                            Image = "profilepic5.jpg",
                            LastName = "Martin",
                            PhoneNumber = "987-654-3250",
                            UserId = "15"
                        });
                });

            modelBuilder.Entity("api.Models.Notification", b =>
                {
                    b.Property<int>("NotificationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationsId"));

                    b.Property<string>("NotificationsInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationsId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("api.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShipmentId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("SellerId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("api.Models.TransactionHistory", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionHistory");
                });

            modelBuilder.Entity("api.Models.WatchList", b =>
                {
                    b.Property<int>("WatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WatchId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.ActivityLog", b =>
                {
                    b.HasOne("api.Models.Action", "Action")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Auction", b =>
                {
                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("api.Models.BiddingHistory", b =>
                {
                    b.HasOne("api.Models.Auction", "Auction")
                        .WithMany("Biddings")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", "Bidder")
                        .WithMany()
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("api.Models.Business", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithOne("Business")
                        .HasForeignKey("api.Models.Business", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Individual", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithOne("Individual")
                        .HasForeignKey("api.Models.Individual", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Notification", b =>
                {
                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Shipment", b =>
                {
                    b.HasOne("api.Models.Auction", "Auction")
                        .WithMany("Shipments")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("api.Models.TransactionHistory", b =>
                {
                    b.HasOne("api.Models.Auction", "Auction")
                        .WithMany("Transactions")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.WatchList", b =>
                {
                    b.HasOne("api.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Action", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("api.Models.ApplicationUser", b =>
                {
                    b.Navigation("Business")
                        .IsRequired();

                    b.Navigation("Individual")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Auction", b =>
                {
                    b.Navigation("Biddings");

                    b.Navigation("Shipments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
